Bootstrap: docker
From: python:3.11

%environment
    export PATH=/app:$PATH
    export DATABASE_URL=sqlite:////capstor/store/cscs/swissai/a06/users/group_06/production.db

%files
    requirements.txt /app/requirements.txt

%post
    mkdir -p /app
    cd /app
    pip install --no-cache-dir --upgrade -r /app/requirements.txt

%runscript
    make start
