"""Add non_standard_status_codes table

Revision ID: 43a7fd63adfb
Revises: b68d8fc8f8cf
Create Date: 2024-11-21 17:32:56.430258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '43a7fd63adfb'
down_revision: Union[str, None] = 'b68d8fc8f8cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
