"""update db

Revision ID: 516709d1a243
Revises: de366b6113f7
Create Date: 2024-12-05 13:36:03.498519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '516709d1a243'
down_revision: Union[str, None] = 'de366b6113f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraped_pages', sa.Column('content_formatted_with_markdown', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraped_pages', 'content_formatted_with_markdown')
    # ### end Alembic commands ###
