"""Create markdown_pages table

Revision ID: 844fdafdbbc9
Revises: cdc55d03f354
Create Date: 2024-11-18 20:56:40.595030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '844fdafdbbc9'
down_revision: Union[str, None] = 'cdc55d03f354'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
