"""change pdf model to fit md

Revision ID: a81d7efe8893
Revises: 27f6f4997933
Create Date: 2024-11-19 20:23:42.680807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'a81d7efe8893'
down_revision: Union[str, None] = '27f6f4997933'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdf_links', sa.Column('metadata_dict', sa.JSON(), nullable=True))
    op.add_column('pdf_links', sa.Column('referenced_links', sa.JSON(), nullable=True))
    op.add_column('pdf_links', sa.Column('referenced_images', sa.JSON(), nullable=True))
    op.add_column('pdf_links', sa.Column('md_text', sa.Text(), nullable=True))
    op.add_column('pdf_links', sa.Column('bin', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass    
    # ### end Alembic commands ###
