"""Schema to parse pdf

Revision ID: d5d1947f0047
Revises: 288b9da65e55
Create Date: 2024-11-25 11:07:16.418968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd5d1947f0047'
down_revision: Union[str, None] = '288b9da65e55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdf_links', sa.Column('metadata_dict', sa.JSON(), nullable=True))
    op.add_column('pdf_links', sa.Column('referenced_links', sa.JSON(), nullable=True))
    op.add_column('pdf_links', sa.Column('referenced_images', sa.JSON(), nullable=True))
    op.add_column('pdf_links', sa.Column('md_text', sa.Text(), nullable=True))
    op.add_column('pdf_links', sa.Column('bin', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pdf_links', 'bin')
    op.drop_column('pdf_links', 'md_text')
    op.drop_column('pdf_links', 'referenced_images')
    op.drop_column('pdf_links', 'referenced_links')
    op.drop_column('pdf_links', 'metadata_dict')
    # ### end Alembic commands ###
